sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: BFzR9x8hy3R1DIqi2cb0Bv0+SgagPerIRHBS+E+ghWZPSwZ0vki2WrKstwvHxW6Q/gUmELLTLLBVufq/2KHT5P6D3XspLJzbBf9wvda84jAjzeesqmAckskwWRHMogPCpUgBcrJ0d5x++eP+ifHiTKo3ARCNfY07vz5+V7Uqof2Id0PdgQ8Olm0j0/3gbHFUmAc2JEJv8RpguAOS3kEHBdOe61YXkqiW3528aQA75/02sa2vK8lMETf7S8EypAZ8xA8cU74kF58fkKn0+C+RGF/RX0O+OXwnWrd9OZqqfkP5wbZk9atIeNRiPQ6o0PvxdqX3Iy22mNx8bDMY+fE85fHTdWUbxodzd0/NF+a++beVUe7KYeRJdoWkP+GLsrQ//9xHh6inuaSu3K7oR4iQceOQ4RqyzMV5vVcWLL2d3HWj+1tc71WosAv40bXg5ileVCS6UxD/t27XQRquVqRe1hOYQ+ILxRjxQGjUDWXFeC9gPnRNdhN9tQThO+fzV36ZNkDnUFcdJ6MGEXhNsXTA8MJgnbtRigILDyQRq9cM84dCHB4ELsxhiTC23dfAL4u9OvhEoDm6DjhXNo/fknpVtgRfCNR6435Agc+5soU82hiZKyTgVXIhkPKePpInFxohpEPWIwwHfzKYA8tXcN1vI6W5IIDqiIFOOT45GTi9tPs=
