sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: dfG3TPoSl+8F7gW59+RJjUbPeDgTCdUl6VMSfJdJLZoCXlsEeU8Trwot6cJcy77NyJvnseJUa5qtW1MTKec0Gl6jT7gDmLu5lmJd5UBxpM5FqHYDtBkr/RXW0dV6CHoOlYZoBxobXXq6gmtnAc6Of7XUKugVQU0IKU2LYAZTJKOahU9PFGxc5I88PjFnixT5/+6R1d2pasZm2IDRkWo4HzneAswr2Qxx6AQRYa55/7L41/xv1sjwCZY3aT1Lc3xdsPZZTL0IQgA2O0ehI+W+BR7GjU9sX/1hJljfPmdXtHGPBnAqjkxijjPDlwvjkZ9MjAsmfMsQrHYVrVupehQArsdJ78R4b8+HU1Ca8lEB+EOjl0DWOOFnLEdys57n9lZ4uGReQNEDBIn9WqpPVGXBMX7XrFeHEkqE1J0DJZCwZyAzOL1xJjOOQWU9db/ChSKblhHlwPfxhRVsBTmFZbG2/7ur/NFMjyI4XvRX77a7Hj00SMKvSOJm3bsEoYxr6Q072LTAhIJ3wSKnyZHWWXjk18Y0/Nc1R/B8wHXJbO7kuPUMrZpllrzY00moI96+z48ObeEF//W6AOB94Klx1L33chozL2yqR7G0jnlEelW7TJVfShIsMmIty+YxvHW+4yb+zYVyd0YIsSDAQDJrg2UVwxLJ8BuDN5wE1snF5BApENw=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: BFzR9x8hy3R1DIqi2cb0Bv0+SgagPerIRHBS+E+ghWZPSwZ0vki2WrKstwvHxW6Q/gUmELLTLLBVufq/2KHT5P6D3XspLJzbBf9wvda84jAjzeesqmAckskwWRHMogPCpUgBcrJ0d5x++eP+ifHiTKo3ARCNfY07vz5+V7Uqof2Id0PdgQ8Olm0j0/3gbHFUmAc2JEJv8RpguAOS3kEHBdOe61YXkqiW3528aQA75/02sa2vK8lMETf7S8EypAZ8xA8cU74kF58fkKn0+C+RGF/RX0O+OXwnWrd9OZqqfkP5wbZk9atIeNRiPQ6o0PvxdqX3Iy22mNx8bDMY+fE85fHTdWUbxodzd0/NF+a++beVUe7KYeRJdoWkP+GLsrQ//9xHh6inuaSu3K7oR4iQceOQ4RqyzMV5vVcWLL2d3HWj+1tc71WosAv40bXg5ileVCS6UxD/t27XQRquVqRe1hOYQ+ILxRjxQGjUDWXFeC9gPnRNdhN9tQThO+fzV36ZNkDnUFcdJ6MGEXhNsXTA8MJgnbtRigILDyQRq9cM84dCHB4ELsxhiTC23dfAL4u9OvhEoDm6DjhXNo/fknpVtgRfCNR6435Agc+5soU82hiZKyTgVXIhkPKePpInFxohpEPWIwwHfzKYA8tXcN1vI6W5IIDqiIFOOT45GTi9tPs=
